language: bash

services: docker

env:
  - VERSION=7.2

script:
  - |
    docker run \
      --rm \
      --volume "$(pwd)":/app \
      --workdir /app \
      finalgene/hadolint:latest "${VERSION}/Dockerfile" \
    && docker build --tag "php-fpm:${VERSION}" "${VERSION}"

after_script:
  - docker images
